apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks-mon"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - worker0.ocpd.stholdco.com
            - worker1.ocpd.stholdco.com
            - worker2.ocpd.stholdco.com
  storageClassDevices:
    - storageClassName: "local-sc-mon"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/sdb
---
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks-osd"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - worker0.ocpd.stholdco.com
            - worker1.ocpd.stholdco.com
            - worker2.ocpd.stholdco.com
  storageClassDevices:
    - storageClassName: "local-sc-osd"
      volumeMode: Block
      devicePaths:
        - /dev/sdc
        - /dev/sdd
